### ISSUE TITLE
Is there an API for flight Images and Logos?

### ISSUE THREAD

**Issue by Travelexpro-official** [tsolakoua/amadeus-hotel-images-python#2]
I was able to locate api for hotel but not the flight.

**Comment by tsolakoua** [comment]
Amadeus for Developers doesn't offer such an API.

**Comment by Travelexpro-official** [comment]
So the other travel companies they add these manually?

**Comment by tsolakoua** [comment]
I believe there must be other API platforms providing airline logos.
